global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'node'
  static_configs:
  - targets: ['node_exporter:9100']

- job_name: 'processes'
  static_configs:
  - targets: ['process_exporter:9256']
